### ISSUE TITLE
Break the hard links in the recipe

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/psycopg2-feedstock#2]
The recipe (if I'm reading it correctly) uses install_name_tool on Mac to change some files from other packages. It should break the hard links first, so that if someone builds this package it doesn't corrupt their package cache. 

See https://github.com/conda-forge/staged-recipes/pull/1162/files/a12ed4978c2b215d2583d324547113bebe53aa2a#r75533371

**Comment by xylar** [comment]
This appears to have been fixed in https://github.com/conda-forge/psycopg2-feedstock/pull/40
