### ISSUE TITLE
Figure out a way to shim psycopg2-binary?

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/psycopg2-feedstock#37]
Thanks for packaging `psycopg2`!

On a number of complex feedstocks, e.g. https://github.com/conda-forge/dagster-feedstock, we can't use `pip check` because psycopg2-binary is not available as a distribution, even though they both populate `site-packages/psycopg2`.

This has also lead to further confusion, including a new staged-recipes PR: https://github.com/conda-forge/staged-recipes/pull/12071

Perhaps there would be a way to make a `psycopg2-binary` in `outputs` (with a basically-empty distribution) that hard-pinned to the `psycopg2` version? Seems kind of dirty, and might create other problems, I guess...

**Comment by xylar** [comment]
I'm running into this issue as well: https://github.com/conda-forge/staged-recipes/pull/14087/files#r582850104

It would be great to have a solution.  I'm using a patch to rename `psycopg2-binary` to `psycopg2` in the source package but this isn't a great solution.

**Comment by chrisjsewell** [comment]
Fancy seeing you here @bollwyvl 😉, did you find any half-decent solution for this?

**Comment by bollwyvl** [comment]
nope, still have nothing to show for it.

**Comment by xylar** [comment]
I believe #42 should take care of this.

**Comment by chrisjsewell** [comment]
thanks!

**Comment by xylar** [comment]
False alarm, as @bollwyvl pointed out, my "fix" wasn't going to solve the problem.
