### ISSUE TITLE
psycopg-binary and psycopg-pool

### ISSUE THREAD

**Issue by thewchan** [conda-forge/psycopg2-feedstock#99]
### Comment:

If upstream requires both `psycopg-binary` and `psycopg-pool`, are these currently provided by this feedstock at all implicitly?

Ref here:

**Comment by xylar** [comment]
My understanding is that the `psycopg` conda package should be equivalent in functionality to `psycopg-binary`.  `psycopg-binary` (which should be installed as ``psycopg[binary]` is only a useful concept on PyPI, where it contains statically linked versions of all the dependency libraries.  We don't do that on conda-forge, we provide the dependencies as shared libraries.

See: https://www.psycopg.org/psycopg3/docs/basic/install.html

My understanding is that `psycopg-pool` is a separate package with its own development cycle.  If you would like to have that package, it will need to be added via https://github.com/conda-forge/staged-recipes.  If you do add it, I would be happy to be a maintainer.

See: https://github.com/psycopg/psycopg/?tab=readme-ov-file#hacking

> The psycopg_pool directory contains the [connection pools](https://www.psycopg.org/psycopg3/docs/advanced/pool.html) implementations. This is kept as a separate package to allow a different release cycle.

**Comment by thewchan** [comment]
I think trying to get psycopg_pool up might be a bit much for me given how involved it is to get pyscopg itself up, but hopefully someone else feels inspired to do so!

**Comment by xylar** [comment]
Okay, I can put it on my to-do list.  Not sure when it might actually happen, maybe this weekend?

**Comment by thewchan** [comment]
@xylar no rush at all! Appreciate it

**Comment by xylar** [comment]
Adding the recipe here.  It's pretty straightforward compared with `psycopg` and `psycopg-c`.
https://github.com/conda-forge/staged-recipes/pull/24993

**Comment by xylar** [comment]
This is complete so I'll close the issue.  @thewchan, let me know if you run into trouble.
